export const PRIVATE_HOUSE_SERVICES = [
  "In a last minute",
  "After party",
  "Custom cleaning",
  "Airbnb",
  "Move in/out",
  "Eco cleaning",
  "Regular",
  "Deep",
];

export const OWN_SUPPLES_SERVICE_NAME = "Own_supplies_sub_service";

export const CITIES = [
  { name: "Kraków", price: 0 },
  { name: "Wieliczka", price: 30 },
  { name: "Skawina", price: 30 },
  { name: "Niepolimice", price: 30 },
  { name: "Zielonki", price: 30 },
  { name: "Modlniczka", price: 30 },
  { name: "Liszki", price: 30 },
  { name: "Kryspinow", price: 30 },
  { name: "Cholerzyn", price: 30 },
  { name: "Zabierzow", price: 30 },
  { name: "Wegrzce", price: 30 },
  { name: "Swoszowice", price: 30 },
  { name: "Mogilany", price: 30 },
  { name: "Michałowice", price: 40 },
  { name: "Luborzyca", price: 30 },
  { name: "Balice", price: 30 },
  { name: "Libertów", price: 30 },
  { name: "Modlnica", price: 30 },
  { name: "Wołowice", price: 50 },
  { name: "Węgrzce Wielkie", price: 30 },
  { name: "Bibice", price: 30 },
  { name: "Kozierów", price: 50 },
  { name: "Piekary", price: 30 },
  { name: "Skala", price: 50 },
  { name: "Krzywaczka", price: 60 },
  { name: "Książniczki", price: 30 },
  { name: "Wrząsowice", price: 30 },
  { name: "Rudawa", price: 50 },
  { name: "Szczyglice", price: 30 },
  { name: "Jerzmanowice", price: 50 },
  { name: "Stojowice", price: 60 },
  { name: "Chrzanów", price: 100 },
  { name: "Rudno", price: 60 },
  { name: "Tenczynek", price: 60 },
  { name: "Ostrężnica", price: 60 },
  { name: "Czajowice", price: 50 },
  { name: "Czasław", price: 100 },
  { name: "Trojanowice", price: 30 },
  { name: "Czarnochowice", price: 30 },
  { name: "Łuczyce", price: 40 },
  { name: "Ryczów", price: 80 },
  { name: "Wielkie Drogi", price: 60 },
  { name: "Jaśkowice", price: 70 },
  { name: "Budzyń", price: 30 },
  { name: "Morawica", price: 30 },
  { name: "Rzeszotary", price: 40 },
  { name: "Kokotów", price: 30 },
  { name: "Miechów", price: 70 },
  { name: "Krzeszowice", price: 50 },
  { name: "Myślenice", price: 50 },
  { name: "Brzeźnica", price: 50 },
];
